-- Se elimina la tabla accidentes_no si existiera
DROP TABLE IF EXISTS accidentes_no;

-- Se crea la tabla accidentes_no definiendo los campos
CREATE TABLE public.accidentes_no (
	id_num int8 NULL,
	ind_accda int4 NULL,
	nombre_ind_accd varchar(50) NULL,
	ind_acciv int4 NULL,
	nombre_ind_acciv varchar(50) NULL,
	total_mu30df int4 NULL,
	total_hg30df int4 NULL,
	total_hl30df int4 NULL,
	fecha_accidente date NULL,
	hora_accidente time NULL,
	mes_1f int4 NULL,
	nombre_mes varchar(50) NULL,
	anyo int4 NULL,
	ccaa_1f int4 NULL,
	nombre_ccaa varchar(50) NULL,
	provincia_1f int4 NULL,
	nombre_provincia varchar(50) NULL,
	cod_municipio int4 NULL,
	nombre_municipio varchar(50) NULL,
	carretera varchar(50) NULL,
	km float4 NULL,
	sentido_1f int4 NULL,
	nombre_sentido varchar(50) NULL,
	tipo_via_3f int4 NULL,
	nombre_tipo_via varchar(50) NULL,
	titularidad_via_2f int4 NULL,
	nombre_titularidad_via varchar(50) NULL,
	tipo_animal_1f int4 NULL,
	nombre_tipo_animal_1f varchar(50) NULL,
	tipo_animal_2f int4 NULL,
	nombre_tipo_animal_2f varchar(50) NULL,
	longitud float8 NULL,
	latitud float8 NULL,
	geom public.geometry NULL,
	dia_semana int4 NULL,
	nombre_dia_semana varchar NULL,
	parte_dia varchar NULL,
	luna int4 NULL,
	prec float8 NULL,
	tmin float8 NULL,
	tmax float8 NULL,
	sol float8 NULL,
	uso_suelo varchar NULL,
	altitud float8 NULL,
	pendiente float8 NULL,
	taxonkey varchar(50) NULL,
	tipo_dia varchar NULL,
	tmed float8 NULL,
	imd_total float8 NULL,
	maxspeed int4 NULL
);