-- Se elimina la tabla mapa_forestal si existiera
DROP TABLE IF EXISTS mapa_forestal;

-- Se crea la tabla mapa_forestal definiendo los campos
CREATE TABLE public.mapa_forestal (
	id int4 NOT NULL DEFAULT nextval('mapa_forestal_spain_id_seq'::regclass),
	geom public.geometry(multipolygon, 4326) NULL,
	poligon int4 NULL,
	prov_mfe50 int4 NULL,
	ccaa_mfe50 int4 NULL,
	tfcctot varchar(254) NULL,
	tfccarb varchar(254) NULL,
	fcc_pond varchar(254) NULL,
	tipestr varchar(254) NULL,
	distrib varchar(254) NULL,
	for_man varchar(254) NULL,
	sp1 varchar(254) NULL,
	o1 varchar(254) NULL,
	e1 varchar(254) NULL,
	sp2 varchar(254) NULL,
	o2 varchar(254) NULL,
	e2 varchar(254) NULL,
	sp3 varchar(254) NULL,
	o3 varchar(254) NULL,
	e3 varchar(254) NULL,
	definicion varchar(75) NULL,
	clas_ifn varchar(254) NULL,
	usos_suelo varchar(75) NULL,
	clasmfe_if varchar(254) NULL,
	usos_gener varchar(20) NULL,
	tsp1 varchar(4) NULL,
	tsp2 varchar(4) NULL,
	tsp3 varchar(4) NULL,
	tipo_bosqu varchar(1) NULL,
	id_forarb varchar(254) NULL,
	cla_forarb varchar(8) NULL,
	nom_forarb varchar(100) NULL,
	regbio varchar(4) NULL,
	shape_leng float8 NULL,
	shape_area float8 NULL,
	layer varchar(254) NULL,
	"path" varchar(254) NULL,
	CONSTRAINT mapa_forestal_spain_pkey PRIMARY KEY (id)
);